name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: T2
      id: t2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T2
        setup-command: ''
        command: cat ejercicio02.sql | (( $(grep -cE 'dim|fact') < 3 )) && exit 1
        timeout: 10
        max-score: 5
    - name: T2
      id: t2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T2
        setup-command: ''
        command: cat ejercicio02.sql | (( $(grep -cE 'dim|fact') < 3 )) && exit 1
        timeout: 10
    - name: T3
      id: t3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T3
        setup-command: ''
        command: cat ejercicio03.sql | (( $(grep -cE 'dim|fact') < 3 )) && exit 1
        timeout: 10
    - name: T4
      id: t4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T4
        setup-command: ''
        command: cat README.md  | (( $(grep -c 'Mermaid') < 3 )) && exit 1
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T2_RESULTS: "${{steps.t2.outputs.result}}"
        T3_RESULTS: "${{steps.t3.outputs.result}}"
        T4_RESULTS: "${{steps.t4.outputs.result}}"
      with:
        runners: t2,t2,t3,t4
